### ISSUE TITLE
Remove environment related files

### ISSUE THREAD

**Issue by andriyun** [skilld-labs/docker-php#17]
Lets remove/move docker-compose.yml, *.sh and *.make.yml and all environments related files to separate repo.

In this case we will have more clear and simpler support process

related to https://github.com/skilld-labs/docker-php/pull/13

**Comment by andypost** [comment]
https://github.com/skilld-labs/skilld-docker-container

**Comment by andypost** [comment]
we still using this scripts on 2 projects, but it makes sense to remove

**Comment by andypost** [comment]
Makefile updated to provide metadata https://github.com/skilld-labs/docker-php/commit/e877bdb8ac77dc187e10a18284e4043370abe3ac
