### ISSUE TITLE
Use single config file

### ISSUE THREAD

**Issue by andriyun** [skilld-labs/docker-php#6]
In install.sh file we write db credentials again
Lets use some yaml parsers to read this values and reuse in scripts

**Comment by andriyun** [comment]
We can use this parser for example https://gist.github.com/pkuczynski/8665367

**Comment by andypost** [comment]
I think that defaults should be configured in `docker-compose.yml` as example Mysql credentials

**Comment by andriyun** [comment]
@andypost can you list what params we have to reuse more?
- mysql
???

**Comment by andypost** [comment]
Outdated
